### ISSUE TITLE
扫码登陆报错，新出现的，之前一直都OK

### ISSUE THREAD

**Issue by RoseEnd** [ClassmateLin/dm-ticket#255]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/src/dm-ticket/src/client.rs:87:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by XliOK** [comment]
同

**Comment by rustdebug** [comment]
QrCodeLoginStatusData {
    result_code: 100,
    qrcode_status: "CONFIRMED",
    st: None,
    login_type: None,
    login_scene: None,
    sid: None,
    cookie2: None,
    return_url: None,
}  https://ipassport.damai.cn/newlogin/qrcode/query.do 返回的结果全是空

**Comment by zhipingch** [comment]
##########请点击确认登录#######		thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /usr/src/dm-ticket/src/client.rs:87:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
